### ISSUE TITLE
problem：

### ISSUE THREAD

**Issue by flamingoXu** [QuantumLab-ZY/HamGNN#16]
Dear Zhong Yang
when try to use openmx_postprocess to convert my openmx.scfout into a overlap.out ,  the program report an err. but the Species.Number looks fine.

(GPU) root@bohrium-11924-1124454:~/test/perturbe/data_caculate/openmc_postprocess# mpirun -n 24 openmx_postprocess ./d1/openmx.scfout 

The number of threads in each node for OpenMP parallelization is 1.

*******************************************************
*******************************************************
 Welcome to OpenMX   Ver. 3.9                           
 Copyright (C), 2002-2019, T. Ozaki                    
 OpenMX comes with ABSOLUTELY NO WARRANTY.             
 This is free software, and you are welcome to         
 redistribute it under the constitution of the GNU-GPL.
*******************************************************
*******************************************************

Species.Number may be wrong.Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.

Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.Species.Number may be wrong.

Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
Species.Number may be wrong.
The recursion method is not supported anymore.

#
# Definition of Atomic Species
#
Species.Number       3
<Definition.of.Atomic.Species
Se   Se7.0-s3p2d2       Se_PBE19
Mo   Mo7.0-s3p2d2       Mo_PBE19
W   W7.0-s3p2d2f1       W_PBE19
Definition.of.Atomic.Species>

#
# Atoms
#
Atoms.Number          54
Atoms.SpeciesAndCoordinates.Unit   Ang # Ang|AU
<Atoms.SpeciesAndCoordinates           # Unit=Ang.
  1  Mo  -0.0286802   1.9385361   3.3761010   7.00   7.00
  2  Mo   3.3626113   1.9288630   3.3860054   7.00   7.00
  3  Mo   0.0189562   7.6608930   3.3874465   7.00   7.00
  4  Mo  -1.6181169   4.7561361   3.4182420   7.00   7.00
  5  Mo   6.6963890   1.9037534   3.4232872   7.00   7.00
  6  Mo  -3.3719035   7.6853933   3.4254761   7.00   7.00
  7  Mo   1.7039942   4.7615691   3.4358513   7.00   7.00
  8  Mo   3.3428237   7.6583756   3.4464608   7.00   7.00
  9  Mo   4.9875423   4.7740001   3.4597375   7.00   7.00
 10  Se   1.6479069   6.6861775   1.6960455   3.00   3.00
 11  Se   6.6620135   3.8516398   1.7150090   3.00   3.00
 12  Se   8.3431634   0.9212830   1.7230284   3.00   3.00
 13  Se  -1.6894806   6.7494416   1.7349048   3.00   3.00
 14  Se   4.9293133   0.9813151   1.7470587   3.00   3.00
 15  Se   1.6218534   0.9402664   1.7546247   3.00   3.00
 16  Se   3.3064606   3.8582844   1.7612616   3.00   3.00
 17  Se   5.0046991   6.7349773   1.7700242   3.00   3.00
 18  Se   0.0134959   3.8758717   1.7898198   3.00   3.00
 19  Se  -0.0214408   3.8453380   5.0316924   3.00   3.00
 20  Se  -1.7057505   6.7500693   5.0422239   3.00   3.00
 21  Se   6.6372654   3.8306564   5.0434805   3.00   3.00
 22  Se   4.9555780   6.7515701   5.0456707   3.00   3.00
 23  Se   3.2974692   3.7934811   5.0594792   3.00   3.00

**Comment by QuantumLab-ZY** [comment]
Your usage of `openmx_postprocess` is incorrect. In the readme file, I never mentioned that `openmx_postprocess` is used to read `.scfout` files; instead, it is used to generate `overlap.scfout` files. The usage of `openmx_postprocess` is similar to that of `openmx`, as it is essentially a modification based on `openmx`. By the way, when pasting parameters and structure files, I recommend using the following format:
```
Atoms.Number 54
Atoms.SpeciesAndCoordinates.Unit Ang # Ang|AU
<Atoms.SpeciesAndCoordinates # Unit=Ang.
1 Mo -0.0286802 1.9385361 3.3761010 7.00 7.00
2 Mo 3.3626113 1.9288630 3.3860054 7.00 7.00
3 Mo 0.0189562 7.6608930 3.3874465 7.00 7.00
4 Mo -1.6181169 4.7561361 3.4182420 7.00 7.00
5 Mo 6.6963890 1.9037534 3.4232872 7.00 7.00
6 Mo -3.3719035 7.6853933 3.4254761 7.00 7.00
```

**Comment by flamingoXu** [comment]
Dear Yang Zhong
Thanks for your answer and . I am sorry for misunderstanding the readme file.
