### ISSUE TITLE
setup.py error

### ISSUE THREAD

**Issue by Drawthe** [QuantumLab-ZY/HamGNN#24]
"graph_data_gen = utils_openmx.graph_data_gen:main"，
            The comma uses full width characters (U+FF0C) instead of the standard half width comma (,)
            
![image](https://github.com/user-attachments/assets/343724d4-4a1e-41cd-b493-c1df3b38c14a)

**Comment by QuantumLab-ZY** [comment]
I apologize for mistakenly using a Chinese comma in line 21 of setup.py when I made modifications several days ago. Simply replacing it with an English comma will resolve this issue.

**Comment by Drawthe** [comment]
Just briefly pointing out the issue for better installation. Thank you for your reply, I will close this question
