### ISSUE TITLE
requirements for conda environment?

### ISSUE THREAD

**Issue by miicck** [QuantumLab-ZY/HamGNN#25]
Hi, would it be possible to get an updated list of requirements for the python environment? I've tried quite hard to get a working environment together (see below) to no avail.

I'm aware of the [uploaded conda environment](https://zenodo.org/records/11064223) mentioned in the README, but it doesn't work on any of the machines I've tried:

![image](https://github.com/user-attachments/assets/ff433361-a06a-4abb-b02d-2ea3c9248db8)

I've also tried building a conda environment with the requirements listed in the README, using the following environment.yml:

```
channels:
  - pyg
  - default
  - conda-forge
requirements:
  - python>=3.8
  - numpy==1.21.2
  - pytorch==1.11.0
  - pyg==2.0.4
  - pytorch-lightning==1.5.10
  - e3nn==0.5.0
  - pymatgen==2022.3.7
  - tensorboard==2.8.0
  - tqdm
  - scipy==1.7.3
  - yaml
```

But conda finds conflicts for this environment:

![image](https://github.com/user-attachments/assets/5d7c3547-dcc7-4e9f-bb37-5b7202035768)

Removing the version restrictions leads to import errors:

![image](https://github.com/user-attachments/assets/0ef84e91-f89d-400d-a633-98ffda997bcf)

I've also tried manually creating a conda.yml that doesn't lead to import errors:

```
channels:
  - pyg
  - defaults
  - conda-forge
dependencies:
  - pyg
  - tqdm
  - yaml
  - numpy
  - scipy
  - pymatgen
  - pytorch-sparse
  - tensorboard
  - e3nn
  - easydict
  - numba
  - llvmlite
  - pytorch-lightning
```
But this leads to some quite nasty looking runtime errors:

![image](https://github.com/user-attachments/assets/2964d827-db97-4e73-8abf-c21fd69e7b22)

**Comment by QuantumLab-ZY** [comment]
Hi, the [uploaded conda environment](https://zenodo.org/records/11064223) should work. The issue you encountered might be due to your system missing the `libcusparse.so.11` shared library, or not having the library path added to your `.bashrc` file. Please check if `libcusparse.so.11` is installed. You can install `cudatoolkit=11.3.1` to obtain this shared library. Once installed, the conda environment should function properly. The screenshot below shows that `libcusparse.so.11` is included in `cudatoolkit=11.3.1`.

![image](https://github.com/user-attachments/assets/1f5beeb1-5e53-4fac-bf24-dc7c9bc05536)

**Comment by miicck** [comment]
Hi @QuantumLab-ZY, thanks for the response. I can't see `libcusparse.so.11` in the screenshot you sent.

For additional context, my plan is to deploy this model to a large number of machines, which belong to various people. They are understandably nervous about using a conda environment downloaded from the internet in this way, rather than setup in a conventional way. An up-to-date `environment.yml` file would be really helpful.

**Comment by QuantumLab-ZY** [comment]
Hi @miicck, I'm sorry, I mistakenly confused libcublas.so.11 with libcusparse.so.11. I'll use `conda env export > environment.yaml` to package the conda environment. I'll first test installing from this environment.yaml file to ensure there are no issues. If everything works well, I'll upload the environment.yaml file.

**Comment by miicck** [comment]
Great, thanks @QuantumLab-ZY!

**Comment by QuantumLab-ZY** [comment]
Hello @miicck,

You can use the [conda environment file](https://github.com/QuantumLab-ZY/HamGNN/blob/main/environment.yaml) to set up the environment by running:

```bash
conda env create -f environment.yaml
```

I've tested it, and HamGNN runs successfully. Let me know if you encounter any issues.

Best,  
Yang Zhong

**Comment by miicck** [comment]
Hi @QuantumLab-ZY I've managed to get a working environment setup - thanks for your help. I've submitted a pull request for a small compatibility issue I ran into along the way https://github.com/QuantumLab-ZY/HamGNN/pull/30
