### ISSUE TITLE
openMX_postprocess installation error static declaration of ‘Print_CubeCData_MO’

### ISSUE THREAD

**Issue by Vahid999** [QuantumLab-ZY/HamGNN#26]
I have installed openMX3.9. The next on the list is openMX_postprocess before installing HamGNN. With gcc, openmpi and mkl, the makefile is

`GSL_lib = /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/Compiler/gcc12/gsl/2.7/lib

GSL_include = /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/Compiler/gcc12/gsl/2.7/include

MKLROOT = /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/imkl/2023.2.0/mkl/2023.2.0

CMPLR_ROOT = /cvmfs/soft.computecanada.ca/easybuild/modules/2023/x86-64-v4/Compiler/gcc12

CC = mpicc -O3   -fopenmp -fcommon -I${MKLROOT}/include/fftw -I${MKLROOT}/include -I${GSL_include} -DDERIVATIVE

FC = mpif90 -O3   -fopenmp -fallow-argument-mismatch  -I${MKLROOT}/include

LIB = ${CMPLR_ROOT}/linux/compiler/lib/intel64_lin/libiomp5.a ${MKLROOT}/lib/intel64/libmkl_blas95_lp64.a ${MKLROOT}/lib/intel64/libmkl_lapack95_lp64.a ${MKLROOT}/lib/intel64/libmkl_scalapack_lp64.a -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a ${MKLROOT}/lib/intel64/libmkl_intel_thread.a ${MKLROOT}/lib/intel64/libmkl_core.a ${MKLROOT}/lib/intel64/libmkl_blacs_intelmpi_lp64.a -Wl,--end-group ${CMPLR_ROOT}/linux/compiler/lib/intel64_lin/libifcoremt.a -lpthread -lm -ldl ${GSL_lib}/libgsl.a`

I get the following error as the make starts:
`mpicc -O3   -fopenmp -fcommon -I/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/imkl/2023.2.0/mkl/2023.2.0/include/fftw -I/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/imkl/2023.2.0/mkl/2023.2.0/include -I/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/Compiler/gcc12/gsl/2.7/include -DDERIVATIVE -I./elpa-2018.05.001 -c openmx.c

openmx.c: In function ‘main’:
openmx.c:779:9: warning: implicit declaration of function ‘Set_initial_Hamiltonian’; did you mean ‘Set_Hamiltonian’? [-Wimplicit-function-declaration]
  779 |         Set_initial_Hamiltonian("stdout", 1, 0, H0, HNL, H);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         Set_Hamiltonian
openmx.c: At top level:

openmx.c:1008:6: warning: conflicting types for ‘Set_initial_Hamiltonian’; have ‘void(char *, int,  int,  double *****, double *****, double *****)’
 1008 | void Set_initial_Hamiltonian(char *mode,
      |      ^~~~~~~~~~~~~~~~~~~~~~~

openmx.c:779:9: note: previous implicit declaration of ‘Set_initial_Hamiltonian’ with type ‘void(char *, int,  int,  double *****, double *****, double *****)’
  779 |         Set_initial_Hamiltonian("stdout", 1, 0, H0, HNL, H);
      |         ^~~~~~~~~~~~~~~~~~~~~~~

openmx.c:1187:13: error: static declaration of ‘Print_CubeCData_MO’ follows non-static declaration
 1187 | static void Print_CubeCData_MO(FILE *fp, dcomplex *data, char *op)
      |             ^~~~~~~~~~~~~~~~~~
openmx.c:85:6: note: previous declaration of ‘Print_CubeCData_MO’ with type ‘void(FILE *, dcomplex *, char *)’
   85 | void Print_CubeCData_MO(FILE *fp, dcomplex *data, char *op);
      |      ^~~~~~~~~~~~~~~~~~

openmx.c:1238:13: error: static declaration of ‘Print_CubeTitle’ follows non-static declaration
 1238 | static void Print_CubeTitle(FILE *fp, int EigenValue_flag, double EigenValue)
      |             ^~~~~~~~~~~~~~~

openmx.c:84:6: note: previous declaration of ‘Print_CubeTitle’ with type ‘void(FILE *, int,  double)’
   84 | void Print_CubeTitle(FILE *fp, int EigenValue_flag, double EigenValue);
      |      ^~~~~~~~~~~~~~~
In file included from openmx.c:67:

openmx_common.h:3539:13: warning: inline function ‘Spherical_Bessel’ declared but never defined
 3539 | inline void Spherical_Bessel( double x, int lmax, double *sb, double *dsb ) ;
      |             ^~~~~~~~~~~~~~~~
make: *** [makefile:202: openmx.o] Error 1`

Is there a way to avoid this error?

Thanks,
Vahid

**Comment by QuantumLab-ZY** [comment]
![image](https://github.com/user-attachments/assets/cf774ac2-ec92-42f2-a39b-d44e31f1c5ee)
Dear Vahid,

Perhaps you can resolve this issue by declaring the mentioned functions as static functions. 

Best wishes,

Yang Zhong

**Comment by Vahid999** [comment]
Dear Yang Zhong,

Thank you for your suggestion. I will declare them as such. I guess this must be a bug.

Best,
Vahid

On Aug 31, 2024, at 11:08 PM, Yang Zhong ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


image.png (view on web)<https://github.com/user-attachments/assets/cf774ac2-ec92-42f2-a39b-d44e31f1c5ee>
Dear Vahid,

Perhaps you can resolve this issue by declaring the mentioned functions as static functions.

Best wishes,

Yang Zhong

**Comment by Vahid999** [comment]
The code compiled with the declaration of static. There are two other locations in openmx.c where the same two functions need to be called static. 

Thank you for your suggestion.
Vahid

**Comment by Vahid999** [comment]
Dear Yang Zhong,

The declaration worked and I had to make the same change in two other locations. I reported this to Github and closed the issue but the website removed my post entirely.

Just wanted to thank you for your suggestion.

Best,
Vahid

On Sep 1, 2024, at 9:50 AM, Vahid Askarpour ***@***.***> wrote:

Dear Yang Zhong,

Thank you for your suggestion. I will declare them as such. I guess this must be a bug.

Best,
Vahid

On Aug 31, 2024, at 11:08 PM, Yang Zhong ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


image.png (view on web)<https://github.com/user-attachments/assets/cf774ac2-ec92-42f2-a39b-d44e31f1c5ee>
Dear Vahid,

Perhaps you can resolve this issue by declaring the mentioned functions as static functions.

Best wishes,

Yang Zhong
