### ISSUE TITLE
openmx.c compilation error resolved

### ISSUE THREAD

**Issue by newplay** [QuantumLab-ZY/HamGNN#3]
When compiling the `openmx_postprocess`, I noticed an incorrect declaration in the `openmx.c` file:
```C
void Print_CubeTitle(FILE *fp, int EigenValue_flag, double EigenValue); // in lines 84
void Print_CubeCData_MO(FILE *fp, dcomplex *data, char *op); // in lines 85
```
However, the accurate function declarations are:

```C
static void Print_CubeTitle(FILE *fp, int EigenValue_flag, double EigenValue); // in lines 1238
static void Print_CubeCData_MO(FILE *fp, dcomplex *data, char *op); // in lines 1187
```
Although I am not proficient in C, it seems that the declarations should be corrected to:

```C
static void Print_CubeTitle(FILE *fp, int EigenValue_flag, double EigenValue); // in lines 84
static void Print_CubeCData_MO(FILE *fp, dcomplex *data, char *op); // in lines 85
```
I made the changes, and the compilation process proceeded successfully. Is this modification reasonable?

**Comment by QuantumLab-ZY** [comment]
I don't encounter any errors when I compile the code using the original version. If you need to make modifications to the code for it to compile successfully, then I believe your change is reasonable and will have the same functionality as the original one.
